export const CHEST = {
  ADD_POTION: {
    REQUEST: 'CHEST/ADD_POTION/REQUEST'
  },
  REMOVE_POTION: {
    REQUEST: 'CHEST/REMOVE_POTION/REQUEST'
  }
}

export const POTION = {
  LIST: {
    REQUEST: 'POTION/LIST/REQUEST',
    SUCCESS: 'POTION/LIST/SUCCESS',
    ERROR: 'POTION/LIST/ERROR'
  }
}
