export const LOGOUT = 'LOGOUT'

export const USER = {
  GET: {
    SUCCESS: 'USER/GET/SUCCESS'
  },
  CREATE: {
    REQUEST: 'USER/CREATE/REQUEST',
    SUCCESS: 'USER/CREATE/SUCCESS',
    ERROR: 'USER/CREATE/ERROR',
    INVALID: 'USER/CREATE/INVALID'
  },
  AUTHENTICATE: {
    REQUEST: 'USER/AUTHENTICATE/REQUEST',
    SUCCESS: 'USER/AUTHENTICATE/SUCCESS',
    COMPLETE: 'USER/AUTHENTICATE/COMPLETE',
    ERROR: 'USER/AUTHENTICATE/ERROR',
    CHECK: 'USER/AUTHENTICATE/CHECK',
    LOGOUT: 'USER/AUTHENTICATE/LOGOUT'
  },
  UPDATE: {
    REQUEST: 'USER/UPDATE/REQUEST',
    SUCCESS: 'USER/UPDATE/SUCCESS',
    ERROR: 'USER/UPDATE/ERROR'
  },
  LIST: {
    REQUEST: 'USER/LIST/REQUEST',
    SUCCESS: 'USER/LIST/SUCCESS',
    ERROR: 'USER/LIST/ERROR'
  }
}
